
project_id = "relqexesmhirdxubfgmy"

[functions.transcribe]
verify_jwt = false
timeout = 60

[functions.test-deepgram-key]
verify_jwt = false

[functions.process-audio]
verify_jwt = false
timeout = 60

